package SiLO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author feral
 */
public class Mainpage extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame
     */
    public Mainpage() {
        
        initComponents();
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        deliveryNoteForm = new DeliveryNoteForm();
        deliveryNoteCtl = new DeliveryNoteCtl(deliveryNoteForm);
        addNewItemForm = new ItemForm(1);
        editItemForm = new ItemForm(2);
        itemCtl = new ItemCtl(addNewItemForm, editItemForm);
        detailInvoicePage = new DetailInvoicePage();
        listInvoiceCtl = new ListInvoiceCtl();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listItem = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        searchItemTF = new javax.swing.JTextField();
        searchItemBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();
        searchInvoiceTF = new javax.swing.JTextField();
        searchInvoiceBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        menuMB = new javax.swing.JMenuBar();
        itemMI = new javax.swing.JMenu();
        invoiceMI = new javax.swing.JMenu();
        deliveryNotesMI = new javax.swing.JMenu();
        createDeliveryNoteMenu = new javax.swing.JMenu();
        viewDeliveryNoteMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Barcode", "Title", "Description", "Manufacturer", "URL"
            }
        ));
        jScrollPane1.setViewportView(listItem);

        addBtn.setText("Add");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        this.addBtn.setVisible(false);

        searchItemTF.setText("search items");
        searchItemTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemTFActionPerformed(evt);
            }
        });

        searchItemBtn.setText("Search Item");
        searchItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchItemBtnMouseClicked(evt);
            }
        });
        searchItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchItemBtnActionPerformed(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(searchItemTF, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchItemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchItemTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchItemBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(editBtn))
                .addContainerGap())
        );

        searchItemBtn.getAccessibleContext().setAccessibleName("searchItemBtn");

        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Invoice Number", "PO Number", "Supplier Name", "Order Date", "Delivery Date", "Status"
            }
        ));
        jScrollPane2.setViewportView(invoiceTable);

        searchInvoiceTF.setText("search invoices");

        searchInvoiceBtn.setText("Search Invoice");
        searchInvoiceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchInvoiceBtnMouseClicked(evt);
            }
        });

        viewBtn.setText("View");
        viewBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(searchInvoiceTF, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                .addComponent(viewBtn)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInvoiceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchInvoiceBtn))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewBtn)
                .addContainerGap())
        );

        itemMI.setText("Item");
        itemMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemMIMouseClicked(evt);
            }
        });
        menuMB.add(itemMI);

        invoiceMI.setText("Invoice");
        invoiceMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoiceMIMouseClicked(evt);
            }
        });
        menuMB.add(invoiceMI);

        deliveryNotesMI.setText("Delivery Notes");

        createDeliveryNoteMenu.setText("Create Delivery Note");
        createDeliveryNoteMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createDeliveryNoteMenuMouseClicked(evt);
            }
        });
        deliveryNotesMI.add(createDeliveryNoteMenu);

        viewDeliveryNoteMenu.setText("View Delivery Notes List");
        deliveryNotesMI.add(viewDeliveryNoteMenu);

        menuMB.add(deliveryNotesMI);

        setJMenuBar(menuMB);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemMIMouseClicked
        //listItemCtl.getListItem();
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        addBtn.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMIMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        itemCtl.requestNewItemForm(); 
    }//GEN-LAST:event_addBtnMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBtnActionPerformed

    private void invoiceMIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoiceMIMouseClicked
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
      //  listInvoiceCtl.getListInvoice();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_invoiceMIMouseClicked

    private void searchItemTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchItemTFActionPerformed

    private void searchItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchItemBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchItemBtnActionPerformed


    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBtnActionPerformed

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        itemCtl.requestEditItemForm(); 
    }//GEN-LAST:event_editBtnMouseClicked

    private void viewBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewBtnMouseClicked
       detailInvoicePage.setVisible(true);
       detailInvoicePage.setSize(300,300);
       invoiceCtl.getInvoiceDescription();
        // TODO add your handling code here:
    }//GEN-LAST:event_viewBtnMouseClicked

    private void searchItemBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchItemBtnMouseClicked
        listItemCtl.searchItem(searchItemTF.toString());
    }//GEN-LAST:event_searchItemBtnMouseClicked

    private void searchInvoiceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchInvoiceBtnMouseClicked
        listInvoiceCtl.searchInvoice(searchInvoiceTF.toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInvoiceBtnMouseClicked

    public void showDetailInvoicePage(Invoice[] invoices){
       detailInvoicePage.setVisible(true);
       detailInvoicePage.setSize(300,300);
    }
    
    private void createDeliveryNoteMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createDeliveryNoteMenuMouseClicked
        deliveryNoteCtl.requestDeliveryNoteForm();
    }//GEN-LAST:event_createDeliveryNoteMenuMouseClicked

    public void showListItem(Item[] items) {
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        addBtn.setVisible(true);
    }
    
      public void showListInvoice(Invoice[] invoices) {
        jPanel2.setVisible(false);
        jPanel1.setVisible(true); 
    }
    
    public void refreshItemList(){
        listItemCtl.getListItem();
        //refresh data on table
    }
    
    public void showInvoiceDescription() {
        detailInvoicePage.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mainpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mainpage().setVisible(true);
            }
        }); 
        
    }

   
    private ItemForm editItemForm;
    private DetailInvoicePage detailInvoicePage;
   private ListInvoiceCtl listInvoiceCtl;
   private InvoiceCtl invoiceCtl;
    private ItemForm addNewItemForm;
    private DeliveryNoteForm deliveryNoteForm;
    private DeliveryNoteCtl deliveryNoteCtl;
    private ListItemCtl listItemCtl;
    private ItemCtl itemCtl;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JMenu createDeliveryNoteMenu;
    private javax.swing.JMenu deliveryNotesMI;
    private javax.swing.JButton editBtn;
    private javax.swing.JMenu invoiceMI;
    private javax.swing.JTable invoiceTable;
    private javax.swing.JMenu itemMI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listItem;
    private javax.swing.JMenuBar menuMB;
    private javax.swing.JButton searchInvoiceBtn;
    private javax.swing.JTextField searchInvoiceTF;
    private javax.swing.JButton searchItemBtn;
    private javax.swing.JTextField searchItemTF;
    private javax.swing.JButton viewBtn;
    private javax.swing.JMenu viewDeliveryNoteMenu;
    // End of variables declaration//GEN-END:variables

  


    
}
